theme = "kanagawa" # "autumn" # "tokyonight_storm" # "everforest_dark"

[editor]
line-number = "relative"
cursorline = true
auto-save = true
rulers = [80, 100, 120]
bufferline = "always"
auto-format = false        # pode ser Ãºtil mais pra frente

[editor.statusline]
separator = "ğŸ‚"
mode.normal = "ğŸ¦œNORMALğŸ¦œ"
mode.insert = "ğŸ¦ƒINSERTğŸ¦ƒ"
mode.select = "ğŸ¦†SELECTğŸ¦†"
left = ["mode", "separator", "file-encoding", "file-type", "separator"]
center = ["workspace-diagnostics", ]
right = ["separator", "separator", "selections", "separator", "position", "position-percentage"]

[editor.lsp]
display-messages = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "underline"

[editor.file-picker]
hidden = false

[editor.whitespace.render]
space = "all"
nbsp = "all"
tab = "all"
tabpad = "all"

[editor.whitespace.characters]
space = "Â·"
nbsp = "â½"
tab = "â†’"
tabpad = ">"

[editor.indent-guides]
render = true
character = "|"

[keys.normal]
space = { q = ":reflow" }

# ğŸğŸ­ğŸ¦”ğŸ§ğŸ¦¢ğŸ¦‰ğŸ¢ğŸ ğŸ•¸ğŸ·ğŸ¦šğŸ“ğŸ¦ğŸ§ğŸ•Š